M48
; DRILL file {KiCad (6.0.4)} date Sat Mar 26 16:13:05 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-26T16:13:05+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.05Y-3.6875
X6.05Y-5.3675
X7.7275Y-3.6875
X7.73Y-5.3675
T0
M30
